config/routes.rb
Rails.application.routes.draw do
  # resources :admins
  root to: 'presences#index', :data => Date.today
  post '/presences/register_presence', to: 'presences#register_presence'
  get 'qr_codes', to: 'students#qr_codes'

  resources :presences
  resources :students
  resources :lessons do
    resources :call_lists
  end
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :student
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /presences
  # GET /presences.json
  def index
    @presences = Presence.where(date: params[:data])
    @students = Student.all
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new
  end

  # GET /presences/1/edit
  def edit
  end

  # POST /presences
  # POST /presences.json
  def create
    @presence = Presence.new(presence_params)

    respond_to do |format|
      if @presence.save
        format.html { redirect_to @presence, notice: 'Presence was successfully created.' }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html { render :new }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1
  # PATCH/PUT /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence.destroy
    respond_to do |format|
      format.html { redirect_to presences_url, notice: 'Presence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register_presence 
    admin = Admin.find_by_username(params[:username])
    return head :not_found unless admin.present?
    if admin.password == params[:password]
      student = Student.find_by(registration: params[:registration])
      @presence = Presence.new({ is_present: true, date: Date.today, student_id: student.id })
      @presence.save
    else
      head :unauthorized
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presence_params
      params.require(:presence).permit(:is_present, :date, :student_id)
    end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<%= form_for(@presence, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @presence.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@presence.errors.count, "error") %> prohibited this presence from being saved:</h4>

      <ul>
      <% @presence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Presente", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_present, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Data", class: "col-sm-2 control-label" %>
    
    <div class="col-sm-10">
      <%= f.date_select :date, :start_year=>Date.today.year, :end_year=>Date.today.year, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Aluno", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.select :student_id, Student.all.collect { |student| [student.name, student.id] } %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Enviar" %>
    </div>
  </div>
<% end %>

app/views/presences/edit.html.erb
<div class="page-header">
  <%= link_to presences_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @presence, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar presença</h1>
</div>

<%= render 'form' %>

app/views/presences/index.html.erb
<div class="page-header">
  <%= link_to new_presence_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nova presença
  <% end %>
  <h1>Lista de presença</h1>
</div>

<form action="/presences">
  <%= label_tag("Data:") %>
  <input id="date" type="date" name="data" value="<%= params[:data] %>"/>
  <%= submit_tag "Buscar", class: "btn btn-primary" %>
</form>

</br></br>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Matrícula</th>
            <th>Turma</th>
            <th>Presença</th>
      </tr>
    </thead>

    <tbody> 
      <%= content_tag_for(:tr, @students) do |student| %>
            <td><%= student.name %></td>
            <td><%= student.registration %></td>
            <td><%= student.lesson.name %></td>
            <td><%= student.is_present(@presences)  %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/presences/new.html.erb
<div class="page-header">
  <%= link_to presences_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Nova presença</h1>
</div>

<%= render 'form' %>

app/views/presences/show.html.erb
<div class="page-header">
  <%= link_to presences_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_presence_path(@presence), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar presença</h1>
</div>

<dl class="dl-horizontal">
  <dt>Presente:</dt>
  <dd><%= @presence.is_present %></dd>

  <dt>Data:</dt>
  <dd><%= @presence.date %></dd>

  <dt>Aluno:</dt>
  <dd><%= @presence.student.name %></dd>

</dl>