config/routes.rb
Rails.application.routes.draw do
  # resources :admins
  root to: 'presences#index', :data => Date.today
  post '/presences/register_presence', to: 'presences#register_presence'
  get 'qr_codes', to: 'students#qr_codes'

  resources :presences
  resources :students
  resources :lessons do
    resources :call_lists
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :students
  has_many :call_lists
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:name)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= form.label "Nome" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Criar"%>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editar turma</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Mostrar', @lesson %> |
<%= link_to 'Voltar', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.name %></td>
        <td><%= link_to '&nbsp;&nbsp;&nbsp;&nbsp;Mostrar'.html_safe, lesson %></td>
        <td><%= link_to '&nbsp;&nbsp;&nbsp;&nbsp;Editar'.html_safe, edit_lesson_path(lesson) %></td>
        <td><%= link_to '&nbsp;&nbsp;&nbsp;&nbsp;Deletar'.html_safe, lesson, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar nova turma', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>Criar Turma</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Voltar', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @lesson.name %>
</p>

<%= link_to 'Editar', edit_lesson_path(@lesson) %> |
<%= link_to 'Voltar', lessons_path %>