config/routes.rb
Rails.application.routes.draw do
  # resources :admins
  root to: 'presences#index', :data => Date.today
  post '/presences/register_presence', to: 'presences#register_presence'
  get 'qr_codes', to: 'students#qr_codes'

  resources :presences
  resources :students
  resources :lessons do
    resources :call_lists
  end
end

app/models/call_list.rb
class CallList < ApplicationRecord
  belongs_to :lesson
end

app/controllers/call_lists_controller.rb
class CallListsController < ApplicationController
  before_action :set_lesson

  def index
    @call_lists = @lesson.call_lists
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end
end

app/views/call_lists/index.html.erb
<div class="page-header">
  <%= link_to new_lesson_call_list_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Call list
  <% end %>
  <h1>Listing call lists</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Id</th>
            <th>Data</th>
            <th>Detalhes</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @call_lists) do |call_list| %>
            <td><%= call_list.id %></td>
            <td><%= call_list.data %></td>
            <td><%= link_to 'Show', lesson_call_list(call_list.lesson, call_list) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/call_lists/show.html.erb
<div class="page-header">
<div class="table-responsive">
  <div class="roll">
    <div class="col-md-12">
      Data: <%= @call_list.date %>
    </div>
  </div>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Matricula</th>
            <th>Lesson</th>
            <th>Presente?</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @call_list.students) do |student| %>
            <td><%= student.name %></td>
            <td><%= student.registration %></td>
            <td><%= student.lesson.name %></td>
            <td><%= student.lesson.name %></td>
            <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>